### PR TITLE
Add support for Phoenix Timezone

### PR DESCRIPTION
**Pull request by bpolly**
This PR adds support for the Phoenix timezone (America/Phoenix according to IANA)

https://time.is/Phoenix

### CODE REVIEW

**Comment by infused** [comment]
Unfortunately, this patch won't work. The tzdata files are rebuilt from source data each month, so they can't be changed manually. In addition you've got changes to the zip code time zones that are invalid. Just one example: 83501 is Lewiston, ID should be Pacific time, not Phoenix time.

**Comment by ckylape** [comment]
@infused could it possible make an assumption with logic similar to:
if the zip starts with 85 or 86 **AND** they do not observe DST; they are "America/Phoenix"?

**Comment by infused** [comment]
That just may work. Let me verify and get back to you.

**Comment by infused** [comment]
I have released version 2.1.0 that adds support for the America/Phoenix time zone.

**Pull request closed without merging**
